# Numpy

https://lectures.quantecon.org/py/numpy.html

In [3]:
import numpy as np
x = np.random.uniform(0, 1, 10000000)
x.mean()

0.49984169394727035

## Numpy Arrays

### Array Methods

In [4]:
a = np.array((4,3,2,1))

In [5]:
a.cumsum()

array([ 4,  7,  9, 10])

## Additional Functionality¶

### Vectorized Functions

In [1]:
import numpy as np

In [2]:
x = np.random.randn(4)
x

array([-0.77065371, -2.15549036,  0.31815074,  0.68807861])

In [5]:
np.where(x > 0, 1, 0)

array([0, 0, 1, 1])

## Exercises

### Exercise 1

Consider the polynomial expression

p(x)=a0+a1x+a2x2+⋯aNxN=∑n=0Nanxn(1)

Earlier, you wrote a simple function p(x, coeff) to evaluate (1) without considering efficiency.

Now write a new function that does the same job, but uses NumPy arrays and array operations for its computations, rather than any form of Python loop.

(Such functionality is already implemented as np.poly1d, but for the sake of the exercise don’t use this class)

Hint: Use np.cumprod()

In [72]:
def p(x, coeff):
    x_1 = np.array([1])
    x_n_1 = np.repeat(x,len(coeff)-1)
    x_n = np.cumprod(np.concatenate([x_1, x_n_1]))
    coeff = np.array(coeff)
    return np.sum(coeff * x_n)

In [73]:
p(3, [2, 4, 5, 6])

221

### Exercise 2

Let q be a NumPy array of length n with q.sum() == 1.

Suppose that q represents a probability mass function.

We wish to generate a discrete random variable x such that P{x=i}=qi.

In other words, x takes values in range(len(q)) and x = i with probability q[i].

The standard (inverse transform) algorithm is as follows:

Divide the unit interval [0,1] into n subintervals I0,I1,…,In−1 such that the length of Ii is qi.
Draw a uniform random variable U on [0,1] and return the i such that U∈Ii.
The probability of drawing i is the length of Ii, which is equal to qi.

We can implement the algorithm as follows